spring.application.name=dieta-api
spring.datasource.url=jdbc:mysql://dieta-mysql:3306/dieta_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=TRUE
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=b2f8a1e46e9f63c6f3a4e90dbe1e8e865a458e33742f8bfa6221bb2ff07a72b0
jwt.expiration=3600000